// <auto-generated />
using System;
using GauntletAI.AgentForge.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Pgvector;

#nullable disable

namespace GauntletAI.AgentForge.Data.Migrations
{
    [DbContext(typeof(AgentForgeDbContext))]
    partial class AgentForgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GauntletAI.AgentForge.Data.Entities.DerivedFact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("ExtractionConfidence")
                        .HasColumnType("double precision");

                    b.Property<string>("FactType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("IngestedDocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("IngestedDocumentId");

                    b.ToTable("derived_facts", (string)null);
                });

            modelBuilder.Entity("GauntletAI.AgentForge.Data.Entities.GuidelineChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)");

                    b.Property<Guid>("GuidelineDocumentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "Content" });

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("Embedding")
                        .HasAnnotation("Npgsql:StorageParameter:ef_construction", 64)
                        .HasAnnotation("Npgsql:StorageParameter:m", 16);

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("GuidelineDocumentId", "Ordinal");

                    b.ToTable("guideline_chunks", (string)null);
                });

            modelBuilder.Entity("GauntletAI.AgentForge.Data.Entities.GuidelineDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("guideline_documents", (string)null);
                });

            modelBuilder.Entity("GauntletAI.AgentForge.Data.Entities.IngestedDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OpenEmrDocumentReferenceId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.HasIndex("PatientId");

                    b.ToTable("ingested_documents", (string)null);
                });

            modelBuilder.Entity("GauntletAI.AgentForge.Data.Entities.IngestionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<Guid?>("IngestedDocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("Status");

                    b.ToTable("ingestion_jobs", (string)null);
                });

            modelBuilder.Entity("GauntletAI.AgentForge.Data.Entities.DerivedFact", b =>
                {
                    b.HasOne("GauntletAI.AgentForge.Data.Entities.IngestedDocument", "Document")
                        .WithMany("DerivedFacts")
                        .HasForeignKey("IngestedDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("GauntletAI.AgentForge.Data.Entities.Citation", "Citation", b1 =>
                        {
                            b1.Property<Guid>("DerivedFactId")
                                .HasColumnType("uuid");

                            b1.PrimitiveCollection<double[]>("BoundingBox")
                                .HasColumnType("double precision[]")
                                .HasColumnName("citation_bbox");

                            b1.Property<string>("FieldOrChunkId")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("citation_field_or_chunk_id");

                            b1.Property<string>("PageOrSection")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("citation_page_or_section");

                            b1.Property<string>("QuoteOrValue")
                                .HasColumnType("text")
                                .HasColumnName("citation_quote_or_value");

                            b1.Property<string>("SourceId")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("citation_source_id");

                            b1.Property<string>("SourceType")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("citation_source_type");

                            b1.HasKey("DerivedFactId");

                            b1.ToTable("derived_facts");

                            b1.WithOwner()
                                .HasForeignKey("DerivedFactId");
                        });

                    b.Navigation("Citation")
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("GauntletAI.AgentForge.Data.Entities.GuidelineChunk", b =>
                {
                    b.HasOne("GauntletAI.AgentForge.Data.Entities.GuidelineDocument", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("GuidelineDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("GauntletAI.AgentForge.Data.Entities.GuidelineDocument", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("GauntletAI.AgentForge.Data.Entities.IngestedDocument", b =>
                {
                    b.Navigation("DerivedFacts");
                });
#pragma warning restore 612, 618
        }
    }
}
